---
title: "Introduction to shaw"
author: Adrienne Marshall
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette will provide a demonstration of making input files for the SHAW hydrologic model. 

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(shaw)
```

Make a minimal set up: 

```{r set up SHAW}
test_model_dir <- paste0(getwd(), "/temp_dir")

inputs <- shaw_inp(model_dir = test_model_dir)


soils_df <- data.frame(depth = seq(0, 2, by = 0.1),
                       sand = 30,
                       silt = 60,
                       clay = 10,
                       rock = 0,
                       organic = 5,
                       bulk_density = 1200,
                       ksat = 50,
                       klat = 0,
                       air_entry = 0,
                       theta_sat = 0.4,
                       n = 1.4,
                       theta_res = 0.05,
                       l = 0.5,
                       alpha = 1.5)

site_file <- shaw_create_sit(model_dir = test_model_dir,
                      start = "2003-01-01", start_hour = 0, end = "2005-12-31",
                      lat_deg = 60, lat_min = 0, slope = 10, aspect = 0, hrnoon = 12, elev = 300,
                      soils_df = soils_df, nres = 5, roughness = 1, measurement_height = 10, ponding = 4,
                      itype = 1, pintrcp = 0.5, xangle = 1,
                      canalb = 0.2, tcrit = 0, min_stomatal_resistance = 150, stomatal_exp = 5, critical_leaf_water = -70,
                      leaf_resist = 10^5, root_resist = 2*10^5,
                      residue_thickness = 5, residue_weight = 6000, residue_fraction = 0.8, residue_albedo = 0.25,
                      iwrc = 3, ivlcbc = 1, itmpbc = 1, lower_bc_temp = 1, nsalt = 0,
                      plant_height = 6, dchar = 0.5, clumping = 0.5, biomass = 4, LAI = 3, rooting = 0.5)

shaw_modify_sit(model_dir = "/Volumes/research_storage2/arctic/arctic_point_modeling/SHAW/test_shaw",
                lat_deg = 65)

moi <- shaw_moi(model_dir = test_model_dir,
                method = "half", iwrc = 3, soil1 = 15)

temp <- shaw_temp(model_dir = test_model_dir,
         soil1 = 15,
         lower_bc = 0,
         temp_obs = data.frame(depth = c(0.1, 0.5, 1),
                               temperature = c(10, 8, 2)))
inputs
site_file
moi
temp
```

